# Generated by Django 2.2.3 on 2019-07-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Acrostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_word', models.CharField(max_length=50)),
                ('poem', models.ManyToManyField(to='acrostic.Adjective')),
            ],
        ),
    ]
