# Generated by Django 2.2.3 on 2019-07-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrostic', '0002_remove_acrostic_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrostic',
            name='poem',
            field=models.TextField(null=True),
        ),
    ]
